version: "3.8"
services:
  php-apache:
    build:
      context: .
    container_name: "php-apache"
    depends_on:
      - "mysql"
    volumes:
      - "./public_html:/var/www/html/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-apache.rule=Host(`lvh.me`, `pmamp.lvh.me`, `example.com`)"
      - "traefik.http.routers.php-apache.entrypoints=web"

  mysql:
    image: "mysql"
    container_name: "mysql"
    volumes:
      - "./dbdata:/var/lib/mysql"
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "rootPASS"
      MYSQL_DATABASE: "dbase"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"
    labels:
      - "traefik.enable=false"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "pma"
    links:
      - "mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`pma.lvh.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  default:
    external:
      name: traefikNetwork
