version: "3.8"
services:
  php-apache:
    build:
      context: .
    container_name: "php-apache"
    depends_on:
      - "mysql"
    volumes:
      - ./var/www:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.php-apache-secure.entrypoints=websecure"
      - "traefik.http.routers.php-apache-secure.rule=Host(`kathy-lin.briskly.ca`)"

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      #- "./mysql_seed.sql:/docker-entrypoint-initdb.d/mysql_seed.sql"
      - ./dbdata:/var/lib/mysql
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: K4thyL1n@2021
      MYSQL_DATABASE: bcit
      MYSQL_USER: klin
      MYSQL_PASSWORD: K4thyL1n@2021
    labels:
      - "traefik.enable=false"
    networks: 
      - database

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: pma
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1024M
      PMA_USER: root
      PMA_PASSWORD: secret
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pma-secure.entrypoints=websecure"
      - "traefik.http.routers.pma-secure.rule=Host(`pma.kathy-lin.briskly.ca`)"
    networks:
      - proxy
      - database

networks:
  proxy:
    external: true
  database:
    external: false
