version: "3.8"
services:
  php-apache:
    build:
      context: .
    container_name: php-apache
    depends_on:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./public_html:/var/www/html/

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
     #- ./seed.sql:/docker-entrypoint-initdb.d/database.sql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "rootPASS"
      MYSQL_DATABASE: "dbase"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma
      links:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - 8080:80
